logger:
  #日志记录等级,DEBUG|INFO|WARN|ERROR|DPANIC|PANIC|FATAL
  level: DEBUG
  #日志文件名称
  filename: /home/ap/safm/log/go/learn_note.log
  #单个日志文件大小,单位MB
  max_size: 256
  #保留旧文件的最大天数
  max_age: 10
  #保留旧文件的最大个数
  max_backups: 10
  #是否使用本地时间,默认UTC
  local_time: true
  #是否压缩日志
  compress: false
  #是否同步输出控制台
  async_console: true

database:
  #数据库驱动名称,mysql|sqlite
  driver: sqlite
  #连接字符串
  #mysql------>username:password@tcp(ip:port)/dbname?charset=utf8mb4&parseTime=True&loc=Local
  dsn: /home/ap/safm/ccbc/conf/learn_note.db
  #是否打印sql语句
  debug: true
  #设置连接可复用的最大时间单位秒
  lifeTime: 40
  #设置空闲连接池中连接的最大数量
  idleConn: 2
  #设置打开数据库连接的最大数量
  openConn: 10